import { Task, Project, Employee } from '../types';

export const demoProjects: Project[] = [
  {
    id: 'project-1',
    name: '产品开发',
    description: '核心产品功能开发',
    color: '#3b82f6',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'project-2',
    name: '市场推广',
    description: '品牌推广与营销活动',
    color: '#10b981',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'project-3',
    name: '客户支持',
    description: '客户服务与技术支持',
    color: '#f59e0b',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'project-4',
    name: '内部培训',
    description: '员工培训与技能提升',
    color: '#8b5cf6',
    createdAt: new Date('2024-02-10'),
  },
];

export const demoEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: '张三',
    email: 'zhangsan@example.com',
    role: '前端开发',
  },
  {
    id: 'emp-2',
    name: '李四',
    email: 'lisi@example.com',
    role: '后端开发',
  },
  {
    id: 'emp-3',
    name: '王五',
    email: 'wangwu@example.com',
    role: '产品经理',
  },
  {
    id: 'emp-4',
    name: '赵六',
    email: 'zhaoliu@example.com',
    role: 'UI设计师',
  },
];

export const demoTasks: Task[] = [
  {
    id: 'task-1',
    title: '完成用户登录功能',
    description: '实现用户登录、注册、忘记密码功能',
    priority: 'high',
    status: 'in-progress',
    projectId: 'project-1',
    assignedTo: 'emp-1',
    dueDate: new Date('2024-12-25'),
    estimatedHours: 8,
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2024-12-20'),
  },
  {
    id: 'task-2',
    title: '设计新版本UI',
    description: '完成产品新版本的UI设计稿',
    priority: 'medium',
    status: 'todo',
    projectId: 'project-1',
    assignedTo: 'emp-4',
    dueDate: new Date('2024-12-28'),
    estimatedHours: 16,
    createdAt: new Date('2024-12-21'),
    updatedAt: new Date('2024-12-21'),
  },
  {
    id: 'task-3',
    title: '优化数据库查询性能',
    description: '分析并优化慢查询',
    priority: 'high',
    status: 'todo',
    projectId: 'project-1',
    assignedTo: 'emp-2',
    dueDate: new Date('2024-12-30'),
    estimatedHours: 12,
    createdAt: new Date('2024-12-22'),
    updatedAt: new Date('2024-12-22'),
  },
  {
    id: 'task-4',
    title: '准备营销活动方案',
    description: '制定Q1季度营销活动计划',
    priority: 'medium',
    status: 'in-progress',
    projectId: 'project-2',
    assignedTo: 'emp-3',
    dueDate: new Date('2024-12-27'),
    estimatedHours: 6,
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2024-12-20'),
  },
  {
    id: 'task-5',
    title: '处理客户反馈',
    description: '回复并处理本周客户反馈',
    priority: 'urgent',
    status: 'todo',
    projectId: 'project-3',
    assignedTo: 'emp-3',
    dueDate: new Date('2024-12-24'),
    estimatedHours: 4,
    createdAt: new Date('2024-12-23'),
    updatedAt: new Date('2024-12-23'),
  },
  {
    id: 'task-6',
    title: 'React 进阶培训',
    description: '组织团队进行React高级特性培训',
    priority: 'low',
    status: 'todo',
    projectId: 'project-4',
    assignedTo: 'emp-1',
    dueDate: new Date('2024-12-29'),
    estimatedHours: 3,
    createdAt: new Date('2024-12-22'),
    updatedAt: new Date('2024-12-22'),
  },
];

